[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
chat-prompts = { path = "../api-server/chat-prompts" }
endpoints = { path = "../api-server/endpoints" }
wasi-nn = { git = "https://github.com/second-state/wasmedge-wasi-nn", branch = "ggml" }
clap = "4.4.6"
once_cell = "1.18"
