[workspace]
members = ["llama-api-server", "prompt", "endpoints"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
endpoints = { path = "endpoints", version = "0.1" }
prompt = { path = "prompt", version = "0.1" }
thiserror = "1"
