[workspace]
members = ["llm-api-server", "prompt", "xin"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
xin = { path = "xin", version = "0.1" }
prompt = { path = "prompt", version = "0.1" }
